openapi: 3.0.2
info:
  title: Mojaloop Thirdparty & DFSP Simulator API
  version: '1.0'
  description: A Mojaloop API that will simulate the out of bound user authentication (OTP or WEB)
    between a DFSP/PISP and their user
  license:
    name: TBD
    url: TBD
servers:
  - url: /
paths:
  /login:
    post:
      tags:
        - DFSPSim
      description: The HTTP request `POST /login` is used to login to DFSP application by providing credentials.
      summary: DFSP user login
      operationId: DFSPLogin
      parameters:
        #Headers
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Accept.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Content-Length.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Content-Type.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/X-Forwarded-For.yaml'
        - name: userName
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/UserName'
        - name: password
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Password'
      requestBody:
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DFSPLoginRequest'
      responses:
        200:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/200.yaml'
        400:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/400.yaml'
        401:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/401.yaml'
        403:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/403.yaml'
        404:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/404.yaml'
        405:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/405.yaml'
        406:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/406.yaml'
        501:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/501.yaml'
        503:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/503.yaml'
  /authorize:
    post:
      tags:
        - DFSPSim
      description: The HTTP request `POST /authorize` is used to grant consent by a DFSP user.
      summary: DFSP user authorization
      operationId: DFSPAuthorize
      parameters:
        #Headers
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Accept.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Content-Length.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Content-Type.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/X-Forwarded-For.yaml'
        - name: userId
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
        - name: consentRequestId
          in: query
          required: true
          schema:
            $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/schemas/CorrelationId.yaml'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DFSPAuthorizeRequest'
      responses:
        200:
          description: Response containing secret
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DFSPAuthorizeResponse'
              example:
                secret: 'xx auth secret xx'
        400:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/400.yaml'
        401:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/401.yaml'
        403:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/403.yaml'
        404:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/404.yaml'
        405:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/405.yaml'
        406:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/406.yaml'
        501:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/501.yaml'
        503:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/503.yaml'
  /sendOTP:
    post:
      tags:
        - DFSPSim
      description: The HTTP request `POST /sendOTP` is used to send OTP to a DFSP user (most likely through SMS).
      summary: DFSP Send OTP
      operationId: SendOTP
      parameters:
        #Headers
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Accept.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Content-Length.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Content-Type.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/X-Forwarded-For.yaml'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendOTPRequest'
            example:
              userName: 'dfspa.user.name'
              consentRequestId: '3b346cec-47b3-4def-b870-edb255aaf6c3'
              message: '9876'
      responses:
        200:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/200.yaml'
        400:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/400.yaml'
        401:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/401.yaml'
        403:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/403.yaml'
        404:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/404.yaml'
        405:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/405.yaml'
        406:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/406.yaml'
        501:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/501.yaml'
        503:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/503.yaml'
  /verifyOTPorSecret:
    post:
      tags:
        - DFSPSim
      description: The HTTP request `POST /verifyOTPorSecret` is used to verify OTP or Secret received from PISP.
      summary: /verifyOTPorSecret
      operationId: VerifyOTPorSecret
      parameters:
        #Headers
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Accept.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Content-Length.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/Content-Type.yaml'
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/X-Forwarded-For.yaml'
      requestBody:
        description: Perform verification of OTP or Secret
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOTPorSecretRequest'
            examples:
              sample1:
                value:
                  consentRequestId: '3b346cec-47b3-4def-b870-edb255aaf6c3'
                  value: '1234'
              sample2:
                value:
                  consentRequestId: '3b346cec-47b3-4def-b870-edb255aaf6c4'
                  value: 'xx auth secret xx'
      responses:
        200:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/200.yaml'
        400:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/400.yaml'
        401:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/401.yaml'
        403:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/403.yaml'
        404:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/404.yaml'
        405:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/405.yaml'
        406:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/406.yaml'
        501:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/501.yaml'
        503:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/503.yaml'
  /OTPorSecret/{ID}:
    get:
      tags:
        - DFSPSim
      description: The HTTP request `GET /OTPorSecret/{ID}` is used to get OTP or Secret from DFSP.
      summary: Get OTP or Secret for specified consentRequestId
      operationId: GetOTPorSecret
      parameters:
        #Path
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/ID.yaml'
        #Headers
        - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/X-Forwarded-For.yaml'
      responses:
        200:
          description: Response containing details of the OTP or Secret
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOTPorSecretResponse'
              examples:
                sample1:
                  value:
                    value: '1234'
                sample2:
                  value:
                    value: 'xx auth secret xx'
        400:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/400.yaml'
        401:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/401.yaml'
        403:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/403.yaml'
        404:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/404.yaml'
        405:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/405.yaml'
        406:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/406.yaml'
        501:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/501.yaml'
        503:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/503.yaml'
  /store/consentRequests/{ID}:
    parameters:
      #Path
      - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/ID.yaml'
      #Headers
      - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/parameters/X-Forwarded-For.yaml'
    get:
      tags:
        - DFSPSim
      operationId: GetConsentRequest
      summary: GetConsentRequest
      description: |
        The HTTP request `GET /store/consentRequests/{ID}` is used by DFSP to load a specified consentRequest.
      responses:
        200:
          description: Response containing consentRequest details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StoreConsent'
              example:
                scopes:
                  - accountId: dfspa.username.1234
                    actions:
                      - accounts.transfer
                      - accounts.getBalance
                  - accountId: dfspa.username.5678
                    actions:
                      - accounts.transfer
                      - accounts.getBalance
        400:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/400.yaml'
        401:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/401.yaml'
        403:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/403.yaml'
        404:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/404.yaml'
        405:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/405.yaml'
        406:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/406.yaml'
        501:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/501.yaml'
        503:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/503.yaml'
    post:
      tags:
        - DFSPSim
      operationId: StoreConsentRequest
      summary: StoreConsentRequest
      description: |
        The HTTP request `POST /store/consentRequests/{ID}` is used by a DFSP to store consentRequests.
      requestBody:
        description: The consentRequest to store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StoreConsent'
            example:
              scopes:
                - accountId: dfspa.username.1234
                  actions:
                    - accounts.transfer
                    - accounts.getBalance
                - accountId: dfspa.username.5678
                  actions:
                    - accounts.transfer
                    - accounts.getBalance
      responses:
        200:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/200.yaml'
        400:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/400.yaml'
        401:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/401.yaml'
        403:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/403.yaml'
        404:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/404.yaml'
        405:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/405.yaml'
        406:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/406.yaml'
        501:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/501.yaml'
        503:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/responses/503.yaml'

components:
  # TODO: Move to `mojaloop/api-snippets.
  schemas:
    SecretValue:
      title: SecretValue
      type: string
      minLength: 11
      maxLength: 128
    UserId:
      type: array
      items:
        $ref: '../../node_modules/@mojaloop/api-snippets/thirdparty/v1_0/openapi3/components/schemas/AccountAddress.yaml'
      minItems: 1
      description: A long-lived unique account identifier provided by the DFSP
    UserName:
      title: UserName
      type: string
      minLength: 1
      maxLength: 25
    Password:
      title: Password
      type: string
      minLength: 1
      maxLength: 25
    Message:
      title: Message
      type: string
      description: OTP value or error message
    DFSPLoginRequest:
      title: DFSPLoginRequest
      type: object
      description: 'POST /login request'
      properties:
        userName:
          $ref: '#/components/schemas/UserName'
        password:
          $ref: '#/components/schemas/Password'
    DFSPAuthorizeRequest:
      title: DFSPAuthorizeRequest
      type: object
      description: 'POST /authorize request'
      properties:
        userId:
          $ref: '#/components/schemas/UserId'
        consentRequestId:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/schemas/CorrelationId.yaml'
    DFSPAuthorizeResponse:
      title: DFSPAuthorizeResponse
      type: object
      description: 'POST /authorize response'
      properties:
        secret:
          $ref: '#/components/schemas/SecretValue'
      required:
        - secret
    SendOTPRequest:
      title: SendOTPRequest
      type: object
      description: 'POST /sendOTP request'
      properties:
        userName:
          $ref: '#/components/schemas/UserName'
        consentRequestId:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/schemas/CorrelationId.yaml'
        message:
          $ref: '#/components/schemas/Message'
      required:
        - userName
        - consentRequestId
        - message
    VerifyOTPorSecretRequest:
      title: VerifyOTPorSecretRequest
      type: object
      description: 'POST /verifyOTPorSecret request'
      properties:
        consentRequestId:
          $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/schemas/CorrelationId.yaml'
        value:
          oneOf:
            - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/schemas/OtpValue.yaml'
            - $ref: '#/components/schemas/SecretValue'
          description: Contains the OTP or Secret value.
      required:
        - consentRequestId
        - value
    GetOTPorSecretResponse:
      title: GetOTPorSecretResponse
      type: object
      description: 'Get /OTPorSecret/{ID} response'
      properties:
        value:
          oneOf:
            - $ref: '../../node_modules/@mojaloop/api-snippets/fspiop/v1_1/openapi3/components/schemas/OtpValue.yaml'
            - $ref: '#/components/schemas/SecretValue'
          description: Contains the OTP or Secret value.
      required:
        - value
    StoreConsent:
      title: StoreConsent
      type: object
      description: 'store consent details'
      properties:
        scopes:
          type: array
          items:
            $ref: '../../node_modules/@mojaloop/api-snippets/thirdparty/v1_0/openapi3/components/schemas/Scope.yaml'
      required:
        - scopes
